
version: '3' # Docker Compose Version

services:
  angular:
    container_name: ANGULAR_MEDIUM
    build: 
      context: './reyceitas-ang'
      args:
        CLIENT_ID: $CLIENT_ID
        CLIENT_SECRET: $CLIENT_SECRET
        CALLBACK_URL: $CALLBACK_URL
        PRIVATE_KEY: $PRIVATE_KEY
        CERT: $CERT
        PRIVATE_KEY_STR: $PRIVATE_KEY_STR
        CERT_STR: $CERT_STR
        API_URL: $API_URL
    volumes:
      - /app
      - /node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - server
    links:
      - server
    ports:
      - '4200:443'
      - '4201:80'
    networks:
      - app-network

  server:
    container_name: NODEJS_SERVER_MEDIUM
    build: './reyceitas-backend'
    volumes:
      - /node-app
    #- ./reyceitas-backend:/node-app
    #  - ./reyceitas-backend:/node-app
    #  - ./node_modules:/node-app/node_modules
      #- /node-app/node_modules
      #- /uploads
      - ./reyceitas-backend/uploads:/uploads
    environment:
      NODE_ENV: development
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      CALLBACK_URL: $CALLBACK_URL
      PRIVATE_KEY: $PRIVATE_KEY
      CERT: $CERT
    depends_on:
      - db
    links:
      - db
    ports:
      - '8999:8999'
      - '8998:8998'

  db:
    image: 'mongo:4.4.6'
    container_name: MONGODB_MEDIUM
    ports:
      - '27017:27017'
    volumes:
      - ./reyceitas-backend/data/db:/data/db
networks:
  app-network:
    driver: bridge 