FROM node:16-alpine
WORKDIR /app
COPY . .
RUN npm ci && npm run build

ARG API_URL
ARG CLIENT_ID
RUN export API_URL=${API_URL}
RUN export CLIENT_ID=${CLIENT_ID}

CMD npm start
EXPOSE 4201
EXPOSE 80
EXPOSE 443